"""Turn the end-to-end runs' result files into a per-cluster table (and badges).

`test_imagenet_example` writes one JSON file per cluster into `$CLUV_CI_RESULTS_DIR` (see
`record_run` in `tests/test_examples.py`). This script collects them and writes:

- a markdown table on stdout, for `$GITHUB_STEP_SUMMARY`;
- `docs/examples/imagenet-verified.md`, the page the example's README links to, so the
  "verified on" list is generated from real runs instead of maintained by hand;
- one shields.io endpoint file per cluster under `docs/_data/badges/`, so a README badge can
  show a cluster's status without the badge itself needing anywhere to be hosted.

Usage: summarize_example_runs.py <results-dir> [--docs-dir docs]
"""

import argparse
import json
from pathlib import Path

BADGE_COLORS = {"COMPLETED": "brightgreen", "FAILED": "red", "TIMEOUT": "orange"}
# The badges read their own state from the files this script commits, so they need no hosting.
BADGE_URL = (
    "https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/"
    "mila-iqia/cluv/master/docs/_data/badges/imagenet-{cluster}.json"
)


def load_records(results_dir: Path) -> list[dict]:
    records = [
        json.loads(path.read_text()) for path in sorted(results_dir.glob("imagenet-*.json"))
    ]
    return sorted(records, key=lambda record: record["cluster"])


def markdown_table(records: list[dict]) -> str:
    if not records:
        return "No end-to-end runs were recorded (no cluster had a live connection?).\n"
    lines = [
        "| Cluster | State | Job | Runtime | Data | Commit | Date |",
        "|---|---|---|---|---|---|---|",
    ]
    for record in records:
        state = record["state"]
        icon = "✅" if state.startswith("COMPLETED") else "❌"
        data = "real" if record.get("real_data") else "fake"
        lines.append(
            f"| {record['cluster']} | {icon} {state} | `{record['job_id']}` | "
            f"{record['elapsed']} | {data} | `{record['commit']}` | {record['date']} |"
        )
    return "\n".join(lines) + "\n"


def badge_row(records: list[dict]) -> str:
    """A shields.io badge per cluster, pointing at the endpoint files written below."""
    return (
        " ".join(
            f"![{record['cluster']}]({BADGE_URL.format(cluster=record['cluster'])})"
            for record in records
        )
        + "\n"
    )


def write_docs_page(records: list[dict], docs_dir: Path) -> Path:
    page = docs_dir / "examples" / "imagenet-verified.md"
    page.parent.mkdir(parents=True, exist_ok=True)
    page.write_text(
        "# ImageNet example: verified clusters\n\n"
        "<!-- Generated by .github/scripts/summarize_example_runs.py - do not edit by hand. -->\n\n"
        "Every row is a real job submitted by the `examples-end-to-end` workflow with\n"
        "`cluv submit`, with no job script named on the command line: the per-cluster\n"
        "`job_script_path` from the example's `pyproject.toml` is what picked it.\n\n"
        + (badge_row(records) + "\n" if records else "")
        + markdown_table(records)
    )
    return page


def write_badges(records: list[dict], docs_dir: Path) -> None:
    badges_dir = docs_dir / "_data" / "badges"
    badges_dir.mkdir(parents=True, exist_ok=True)
    for record in records:
        state = record["state"]
        (badges_dir / f"imagenet-{record['cluster']}.json").write_text(
            json.dumps(
                {
                    "schemaVersion": 1,
                    "label": record["cluster"],
                    "message": f"{state.lower()} ({record['date']})",
                    "color": BADGE_COLORS.get(state.split()[0], "lightgrey"),
                },
                indent=2,
            )
        )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("results_dir", type=Path)
    parser.add_argument("--docs-dir", type=Path, default=Path("docs"))
    args = parser.parse_args()

    records = load_records(args.results_dir)
    print(markdown_table(records))
    write_docs_page(records, args.docs_dir)
    write_badges(records, args.docs_dir)


if __name__ == "__main__":
    main()
