site_name: cluv Documentation
repo_name: mila-iqia/cluv
repo_url: https://github.com/mila-iqia/cluv
docs_dir: docs
edit_uri: edit/master/docs/


theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - navigation.expand
    - content.code.copy
    - content.code.annotate
markdown_extensions:
  - pymdownx.highlight: # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#configuration
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.magiclink
  - admonition
  - pymdownx.details
  # For annotations https://squidfunk.github.io/mkdocs-material/reference/annotations/?h=annota#annotations
  - attr_list
  - md_in_html
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://docs.pytest.org/en/stable/objects.inv
            - https://docs.python.org/3/objects.inv
          options:
            docstring_style: google
            members_order: source
            annotations_path: brief
            show_docstring_attributes: true
            modernize_annotations: true
            show_source: false
            show_submodules: false
            separate_signature: true
            signature_crossrefs: true
            show_signature_annotations: true
            allow_inspection: true
            backlinks: true
            show_labels: false
