# @package _global_
defaults:
  - override /hydra/launcher: cluv_launcher

hydra:
  mode: MULTIRUN
  run:
    # Output directory.
    # We let Cluv tell us the results directory location (since it depends on the cluster being used, 
    # and whether there a multiple runs per job (job packing) or if job chunking is being used).
    # This is typically resolved to "{cluster.results_path}/{cluster_name}_{job_id}".
    # See `cluv.job.current_run_info` for more details.
    # Note: Hydra "needs" to create a directory _locally_ when launching a sweep, for some reason.
    # It places a `multirun.yaml` file in there, which we don't care about, and we don't know the job id yet
    # when submitting the job, so we just use /tmp.
    dir: ${cluv:results_path,/tmp}
  sweep:
    dir: ${cluv:results_path,/tmp}
    subdir: ${hydra.job.num}

  launcher:
    ## NEW ARGUMENTS for cluv:
    cluster: current
    job_script: scripts/job.sh
    autocommit: false
    # chunking: true  # (Coming soon: Automatically chunk jobs into shorter chunks)
    # vram_gb: 10  # (Coming soon: Automatically pack multiple runs per GPU)
    ## Usual submitit arguments:
    stderr_to_stdout: true
    timeout_min: 60
    gpus_per_node: 1
    cpus_per_task: 2
    mem_gb: 16
